<a href="https://colab.research.google.com/github/samerac123/samer_final_project/blob/main/olive_oil.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
olive_oil_df = pd.read_csv('/shouf_olive_oil_dataset_corrected.csv')

In [3]:
display(olive_oil_df.describe())

,Year,Altitude_m,Annual_Rainfall_mm_year,Spring_Rainfall_mm_season,Summer_Max_Temp_C_avg,Frost_Days_count,Irrigation_L_per_tree,Tree_Age_Years,Tree_Density_per_hectare,Fertilizer_20_20_20_kg_per_tree,Pest_Pressure_Index,Oil_Yield_kg_per_hectare,Olives_Produced_kg_per_hectare
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000
mean,2019.500000,699.765000,1119.374500,247.439000,32.340500,26.882000,365.311255,34.365000,300.350000,4.63925,5.084000,2169.730920,8970.954947
std,2.879489,53.712582,124.228057,25.522755,0.949589,7.835649,357.947721,15.049392,67.944905,1.37135,3.029693,836.909167,3154.354643
min,2015.000000,600.000000,526.300000,127.600000,25.900000,8.400000,0.000000,10.000000,200.000000,2.00000,0.000000,716.960410,3437.079738
25%,2017.000000,672.450000,1087.500000,232.500000,31.900000,21.250000,0.000000,21.000000,233.000000,3.51000,2.400000,1461.716564,6167.432064
50%,2019.500000,696.200000,1142.500000,247.500000,32.400000,27.250000,415.621338,33.500000,316.500000,4.58500,5.000000,2103.507919,9017.419978
75%,2022.000000,738.650000,1187.500000,262.500000,32.900000,32.000000,712.497070,47.250000,344.000000,5.76250,7.800000,2700.164055,11495.497598
max,2024.000000,800.000000,1287.500000,302.500000,33.800000,44.250000,900.000000,60.000000,400.000000,7.00000,9.900000,4462.953725,16298.186755

In [4]:
olive_oil_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Year                             200 non-null    int64
 1   Field_ID                         200 non-null    object
 2   Altitude_m                       200 non-null    float64
 3   Annual_Rainfall_mm_year          200 non-null    float64
 4   Spring_Rainfall_mm_season        200 non-null    float64
 5   Summer_Max_Temp_C_avg            200 non-null    float64
 6   Frost_Days_count                 200 non-null    float64
 7   Irrigation_L_per_tree            200 non-null    float64
 8   Tree_Age_Years                   200 non-null    int64
 9   Tree_Density_per_hectare         200 non-null    int64
 10  Fertilizer_20_20_20_kg_per_tree  200 non-null    float64
 11  Soil_Type                        200 non-null    object
 12  Pest_Pressure_Index              200 non-null    float64
 13  Pruning_Intensity                200 non-null    object
 14  Oil_Yield_kg_per_hectare         200 non-null    float64
 15  Olives_Produced_kg_per_hectare   200 non-null    float64
dtypes: float64(10), int64(3), object(3)
memory usage: 25.1+ KB

In [5]:
olive_oil_df.head()

,Year,Field_ID,Altitude_m,Annual_Rainfall_mm_year,Spring_Rainfall_mm_season,Summer_Max_Temp_C_avg,Frost_Days_count,Irrigation_L_per_tree,Tree_Age_Years,Tree_Density_per_hectare,Fertilizer_20_20_20_kg_per_tree,Soil_Type,Pest_Pressure_Index,Pruning_Intensity,Oil_Yield_kg_per_hectare,Olives_Produced_kg_per_hectare
0,2015,Ammatour_1_Field_1,738.0,1112.5,247.5,32.4,31.75,400.00000,53,344,6.30,Clay,6.8,Heavy,2098.333941,9376.468537
1,2015,Ammatour_2_Field_1,701.7,1112.5,247.5,32.4,31.75,0.00000,30,344,4.29,Clay,3.1,Light,1637.180097,6692.030702
2,2015,Ammatour_1_Field_2,746.7,1112.5,247.5,32.4,31.75,712.49707,13,200,2.60,Loam,7.7,Heavy,1185.442011,5703.731245
3,2015,Ammatour_2_Field_2,796.8,1137.5,262.5,32.2,39.25,900.00000,60,289,7.00,Sandy_Loam,7.7,Light,1992.171704,8782.272115
4,2015,Ammatour_1_Field_3,696.2,1087.5,232.5,32.6,24.25,900.00000,43,233,5.40,Sandy_Loam,5.2,Light,2077.325262,8316.841452